#!/usr/bin/perl -w
$versionRCS='$Header: /home/black/DADS/dads/RCS/editTerms,v 1.8 2004/12/01 16:52:40 black Exp $';
#	      *created  "Wed Oct 15 10:37:48 2003" *by "Paul E. Black"
$versionMod=' *modified "Wed Dec  1 11:48:48 2004" *by "Paul E. Black"';

#-----------------------------------------------------------------------------
#
# Check out, change, and check in terms
#
$useMsg = "use: editTerms [--help] [--version] [--force] *.trm";
$minOperands = 1;
$typUse = "./editTerms `grep -l vertices Terms/*.trm`";
#
# This software was developed at the National Institute of Standards 
# and Technology by employees of the Federal Government in the course 
# of their official duties.  Pursuant to title 17 Section 105 of the 
# United States Code this software is not subject to copyright 
# protection and is in the public domain. 
# 
# We would appreciate acknowledgment if the software is used.
#
# Paul E. Black  paul.black@nist.gov or p.black@acm.org
#	http://hissa.nist.gov/~black/
#
#-----------------------------------------------------------------------------

#------------------------------------------------------------------------------
#	Command line handling
#------------------------------------------------------------------------------

$reason = "Fix comment: no cross refs in AKA";
$editor = "Paul E. Black"; # for *modified line
# check that hard-coded date is current to reduce chance of 
# using old reason and old edits
$checkDate = 1;

while ($#ARGV >= 0) {
    if ($ARGV[0] =~ /^--?h(e(lp?)?)?/) {
	print "$useMsg\n";
	print "    where\n";
	print "\t--version Print version and exit\n";
	print "\t--help    Print this message and exit\n";
	print "\t--force   Check out, etc. even though date differs\n";
	print "\t--        End of options (e.g., term begins with -)\n";
	print "    Check out and edit each file.  Do rcsdiff, so you can review changes, and\n";
	print "    ask if you want to commit them.  Your options are:\n";
	print "\ty - Yes; check in changes, with the hard-coded \"reason\"\n";
	print "\tl - Leave changes, but don't check in\n";
	print "\tn - No; unlock the file and revert to the previous version\n";
	print "\tq - Quit; unlock the file and revert, then quit\n";
	print "    The default is 'n'.\n";
	print "typical use:\n";
	print "    $typUse\n";
	exit 0;
    } elsif ($ARGV[0] =~ /^--?v(e(r(s(i(on?)?)?)?)?)?$/) {
	print "$versionRCS\n";
	print "$versionMod\n";
	exit 0;
    } elsif ($ARGV[0] =~ /^--?f(o(r(ce?)?)?)?$/) {
	$checkDate = 0;
	print "Check in reason is '$reason'\n";
	shift;
    } elsif ($ARGV[0] eq "--") {
	shift;
	last;
    } elsif ($ARGV[0] =~ /^-/) {
	print "unknown option: $ARGV[0]\n";
	print "$useMsg\n";
	exit 1;
    } else {
	# end of options
	last;
    }
}

$numberOfOperands = 1 + $#ARGV;
if ($numberOfOperands < $minOperands) {
    print "Wrong number of operands\n";
    print "$useMsg\n";
    die;
}

#------------------------------------------------------------------------------
#	program proper
#------------------------------------------------------------------------------

# make sure the program is not accidentally rerun without being updated
if ($checkDate && localtime() !~ /Wed Dec  1/) {
    print "The (hard coded) check-in reason is:\n";
    print "\t$reason\n";
    print "REMEMBER TO CHANGE THE CHECK-IN REASON!\n";
    print "\tIt is " . localtime() . "\n";
    die;
}

# convert log history from rlog into $Log (co) format
sub formatLogHistory {
    my $file = shift(@_);
    my $logHistory = "";
    if (! open RLOGO, "rlog $file |") {
	print "rlog error for $file\n";
	return "";
    }

    my $inLogMessage = 0;
    while (<RLOGO>) {
	if (/^-----/ || /^=====/) {
	    $logHistory .= "#\n" if $inLogMessage;
	    $inLogMessage=0;
	}
	$logHistory .= "# $_" if $inLogMessage;

	# handle revision and date lines
	if (/^revision ([0-9.]+)/) {
	    $rev=$1;
	    last if $rev == "1.1"; # Rev 1.1 is just "Initial revision"
	}

	if (/^date: ([^;]+);  author: ([^;]+)/) {
	    $logHistory .= "# Revision $rev  $1  $2\n";
	    $inLogMessage=1;
	}
    }

    close RLOGO;

    return $logHistory
}

foreach $term_file_name (@ARGV) {
    #print "==} $term_file_name\n";

    # make sure the writable file is the same as the latest RCS version
    system "rcsdiff $term_file_name > /dev/null 2>&1";
    if ($?) {
	print "$term_file_name differs from RCS version; skipping!\n";
	next;
    }

    # (try to) check it out: lock & get writable file
    system "echo n | co -l $term_file_name > /dev/null 2>&1";
    if ($?) {
	print "Could not check out $term_file_name; skipping!\n";
	next;
    }

    # edit the term file in place
    if (open TERM, "< $term_file_name") {
	# read whole file
	@term_contents = <TERM>;

	close TERM || print "Cannot close TERM!?!\n";

	#print `ls -l $term_file_name`;

	# look for stuff in the term file
	my $xrefsRefinementsFound = 0;
	my $preXrefsCommentLine = "";
	my $previousLine = "";
	foreach $line (@term_contents) {
	    # does it have refinements of XREFS (IMA, etc.)?
	    if ($line =~ /IMA=/) {
		$xrefsRefinementsFound = 1;
	    }

	    # what is the comment line, if any, just before XREFS?
	    if ($line =~ /XREFS=/ && $previousLine =~ /^#/) {
		$preXrefsCommentLine = $previousLine;
	    }

	    $previousLine = $line;
	}

	# write back an edited version
	$runtime = localtime();
	if (open TERM, "> $term_file_name") {
	    my $justAfterModified = 0;
	    my $blankLineFound = 0;
	    foreach $line (@term_contents) {
		# change *modified
		$line =~ s/[*]modified "[^"]*" [*]by "[^"]*"/*modified "$runtime" *by "$editor"/;

		#----------------------------------------------------
		#	Standard "clean-up" edits
		#----------------------------------------------------

		# add RCS Log line (and history) if missing
		if ($justAfterModified) {
		    if ($line =~ /^# \$Log/) {
			# this term already has an RCS Log keyword
			$justAfterModified = 0;
		    } elsif ($line =~ /^$/) {
			# blank line, be patient
			$blankLineFound = 1;
		    } else {
			# no RCS Log line found, but other stuff found
			print TERM "\n" if (! $blankLineFound);
			print TERM "# \$Log\$\n";

			# add Log history
			print TERM &formatLogHistory($term_file_name);

			print TERM "\n";

			$justAfterModified = 0;
		    }
		}
		if ($line =~ /[*]modified "[^"]*" [*]by/) {
		    $justAfterModified = 1;
		    $blankLineFound = 0;
		}

		# add refinements of XREFS if missing
		if (! $xrefsRefinementsFound) {
		    if ($preXrefsCommentLine eq $line) {
			print TERM << "___XREFS_REFINEMENTS___";

#    These are all comma-separated lists of {cross references}
# Generalization: "I am a kind of ..."
\@IMA=
# Specialization: "... is a kind of me."
\@VARIANT=
# Aggregate parent: "I am a part of or used in ..."
\@IMIN=
# Aggregate child: "... is a part of or used in me."
\@INME=
# Other cross references that don't fit the above.  printed as "See also ..."
___XREFS_REFINEMENTS___
			next;
		    }
		    # add blank line after XREFS
		    if ($line =~ /XREFS=/) {
			$line .= "\n";
		    }
		}

		# fix comment: AKA {cross refs} break autogenerated entries
		$line =~ s/pure names or {cross refs}/pure names/;

		# other clean-up edits
		$line =~ s/^# end$/# end \$Source\$/;
		$line =~ s/HREF=/href=/g;

		#----------------------------------------------------
		#
		#	HERE ARE THE SPECIFIC EDITS WE WANT
		#
		# Remember to change the check-in reason
		#
		#----------------------------------------------------

		$line =~ s|caverphone|Caverphone|g;

		print TERM $line;
	    }

	    close TERM || print "Cannot close TERM after writing!?!\n";
	} else {
	    print "Cannot open $term_file_name to write!?!\n";
	}
    } else {
	print "Cannot open $term_file_name!?!\n";
    }

    # review any changes
    system "rcsdiff $term_file_name";

    while (1) {
	print "Commit (check in)? [ynhlq](n): ";
	$ans = <STDIN>;
	if ($ans =~ /[ynlq]/i || $ans =~ /^$/) {
	    last;
	} else {
	    print "Yes: check in; Leave edits but don't check in; Help: show this message\n";
	    print "No: unlock and revert; Quit: unlock and revert then exit\n";
	}
    } 
    if ($ans =~ /[y]/i) {
	system("echo \"$reason\" | ci -u $term_file_name");
    } elsif ($ans =~ /[l]/i) {
	print "leaving edits as is and locked.  Remember to check in $term_file_name\n";
    } else {
	# (try to) UNLOCK it
	system "echo n | rcs -u $term_file_name";

	# revert
	system "co -f $term_file_name";
    }

    if ($ans =~ /[q]/i) {
	exit;
    }
}

# end of $Source: /home/black/DADS/dads/RCS/editTerms,v $
