#!/usr/bin/perl -w
# $Id: mkterms,v 1.52 2001/08/21 13:54:11 black Exp $
# *created  "Tue Sep  8 11:36:37 1998" *by "Paul E. Black"
# *modified "Tue Aug 21 09:24:40 2001" *by "Paul E. Black"
#
# Collect all terms and format them for web pages.
#	Paul E. Black <paul.black@nist.gov> or <p.black@acm.org>
#	http://hissa.nist.gov/~black/
#    Modified By Fabrizio Fioravanti (search for FF)
#	<fioravan@dsi.unifi.it>, <fioravanti@computer.org>
#	http://www.dsi.unifi.it/~fioravan/
#
#------------------------------------------------------------------------

$useMsg="usage: mkterms [--help] [--all] [--page path] [--url root]";
$minOperands = 0;
$maxOperands = 0;

#------------------------------------------------------------------------
#
# This software was developed at the National Institute of Standards 
# and Technology by employees of the Federal Government in the course 
# of their official duties.  Pursuant to title 17 Section 105 of the 
# United States Code this software is not subject to copyright 
# protection and is in the public domain. 
# 
# We would appreciate acknowledgement if the software is used.
#
# Paul E. Black paul.black@nist.gov
#
#------------------------------------------------------------------------

$justTesting = "";

# true prints information as this runs
$verbose = 1;

# true generates all HTML pages
$writeAllPages = "";

# CONFIGURATION SECTION:
require 'mkcommon';

# - Name of the two-level index web page, less extension (.html),
#	it is written to $WEB_DIR/$WEBPAGE.html
$TWOLEVEL ="terms2";

# the first and ending parts of each entry page
$ENTINTRO="entry.intro";
$ENTCONCL="entry.concl";

#------------------------------------------------------------------------
#
# you should not have to edit anything below this
#
#------------------------------------------------------------------------

#------------------------------------------------------------------------------
#       Command line handling
#------------------------------------------------------------------------------

while ($#ARGV >= 0) {
    if ($ARGV[0] =~ /^--?h(e(lp?)?)?/) {
        print "$useMsg\n";
        print "    where\n";
        print "\t--help    Print this message and exit\n";
        print "\t--all     Write HTML pages for all terms\n";
        print "\t--        End of options\n";
        print "    This creates HTML pages and cross references for terms\n";
        exit 0;
    } elsif ($ARGV[0] =~ /^--?a(ll?)?$/) {
	$writeAllPages = 1;
	shift;
    } elsif ($ARGV[0] =~ /^--?p(a(ge?)?)?$/) {
	shift;
	$WEB_DIR = shift;
    } elsif ($ARGV[0] =~ /^--?u(rl?)?$/) {
	shift;
	$URL_DIR = shift;
    } elsif ($ARGV[0] eq "--") {
        shift;
    } elsif ($ARGV[0] =~ /^-/) {
        print "unknown option: $ARGV[0]\n";
        print "$useMsg\n";
        exit 1;
    } else {
        # end of options
        last;
    }
}

$numberOfOperands = 1 + $#ARGV; # - $optind
if ($numberOfOperands < $minOperands || $maxOperands < $numberOfOperands) {
    print "Wrong number of operands\n";
    print "$useMsg\n";
    die;
}

# so -w doesn't complain about these being used only once
$dummy = $numEntriesRead;	# set in mkcommon
$dummy = $TERMS_DIR;		# set and used in mkcommon
undef $dummy;

# get the year (CCYY), month (01-12), day (01-31), etc.  This is Y2K compliant.
#($sec,$min,$hr,$mday,$mon,$yr,$wday,undef,undef) = localtime;
# SKIMP - timezone (like MDT or EST) not printed
#printf("%3s %3s %2d %02d:%02d:%02d %4d\n",
#        (Sun,Mon,Tue,Wed,Thu,Fri,Sat)[$wday],
#        (Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec)[$mon],
#        $mday, $hr, $min, $sec, 1900+$yr);
$now = localtime;

# copy the file to the file handle
# example: append the contents of $TEMP_FILE to $target
#	open(TARGET, "> $target");
#	&concatenate($TEMP_FILE, TARGET);
#	close(TARGET);
sub concatenate {
    my($filename, $handle) = @_;
    open(FHANDLE, "< $filename")
	|| die("Cannot open $filename\n");
    while (<FHANDLE>) {print $handle $_};
    close(FHANDLE);
}

# read/write by owner, readable by everyone else
umask(0022);

# Step I: read initialization and config files
&readConfigFiles;

# Step II: read term entries
&readTermEntries;

#------------------------------------------------------------------------
#
# Step III: write each entry to its own page and create the main and 
#		two-level web pages in temporary files 
#	a) create a temporary file for the main (combined) index
#		copy the introduction
#	b) create a temporary file for the two-level index
#		and copy the introduction
#
#------------------------------------------------------------------------

sub rewriteXrefs {
    # rewrite cross references ({...}) as href's (to entries, not files)
    #print "STEP 1: $_[0] \n"; # for debugging
    $_[0] =~ s|%|%P|go; # preserve our escape character
    $_[0] =~ s|\\{|%R|go; # escape {'s in HTML markup
    #print "STEP 3: $_[0] \n"; # for debugging
    # rewrite complex references ( {text#xref} ) first
    $_[0] =~ s|{([^}]+)\#([^}]+)}|<a href="\#$2"><em>$1</em></a>|go;
    # now rewrite simple references ( {textref} )
    $_[0] =~ s|{(.+?)}|<a href="\#$1"><em>$1</em></a>|go;
    # change escaped characters back
    $_[0] =~ s|%R|{|go; # unescape {'s for final display
    $_[0] =~ s|%P|%|go;
    #print "STEP 7: $_[0] \n"; # for debugging

    # change entry names to their corresponding files and
    #   report any dangling xrefs
    foreach $xref (split /^.*?href="\#|".*?href="\#|".*?$|^.*$/, $_[0]) {
	next if ($xref eq ""); # above RE starts with a null split
	#print "\nFound $xref\n"; # for debugging
	my $strippedXref = $xref;
	$strippedXref =~ s/\$([^\$]*)\$/$1/go; # strip LaTeX markers
	my $indexXref = $strippedXref;
	if (! defined $entriesForXref{$indexXref}) {
	    # try the singular, i.e., removing a trailing "s"
	    $indexXref =~ s/s$//;
	    if (! defined $entriesForXref{$indexXref}) {
		# try lower case on first character
		$indexXref = $strippedXref; # start again
		substr($indexXref, 0, 1) =~ tr/A-Z/a-z/;
		if (! defined $entriesForXref{$indexXref}) {
		    # try removing a trailing "es"
		    $indexXref = $strippedXref; # start again
		    $indexXref =~ s/es$//;
		    if (! defined $entriesForXref{$indexXref}) {
			print "\n    *****Unknown HyperREFerence to \"$xref\" in $_[1]\n";
			next;
		    }
		}
	    }
	}

	my $xrefKey = $entriesForXref{$indexXref};
	#print "\nit is $xrefKey\n";
	%xrefEntry = %{$entries{$xrefKey}};
	my($xrefFile) = "$xrefEntry{BASEFILENM}.html";

	# quote special RE characters
	my $xrefQ = quoteREpatterns("\#$xref");

	#print "subs is /$xrefQ/$xrefFile/\n"; # for debugging
	$_[0] =~ s/$xrefQ/$xrefFile/;
    }
}

# Rewrite external HREFs to use the NIST "exit script" described at
#	http://webservices.nist.gov/exit_nist.htm
sub rewriteHrefs {
    foreach $xref (split /^.*?href="|".*?href="|".*?$|^.*$/i, $_[0]) {
	next if ($xref eq ""); # above RE starts with a null split
	next if $xref =~ /nist\.gov/; # don't rewrite internal links
	#print "\nFound $xref\n"; # for debugging

	# quote special cgi characters
	my($xrefCGIQ) = $xref;
	$xrefCGIQ =~ s|%|%25|g;
	$xrefCGIQ =~ s| |%20|g;
	$xrefCGIQ =~ s|"|%22|g;
	$xrefCGIQ =~ s|\#|%23|g;
	$xrefCGIQ =~ s|&|%26|g;
	$xrefCGIQ =~ s|\+|%2B|g;
	#$xrefCGIQ =~ s|/|%2F|g;
	$xrefCGIQ =~ s|;|%3B|g;
	$xrefCGIQ =~ s|=|%3D|g;
	$xrefCGIQ =~ s|~|%7E|g;
	my($xrefExit) = "\"http://www.nist.gov/cgi-bin/exit_nist.cgi?url=$xrefCGIQ\"";

	# quote special RE characters
	my $xrefQ = quoteREpatterns("\"$xref\"");

	#print "subs is /$xrefQ/$xrefExit/\n"; # for debugging
	$_[0] =~ s/$xrefQ/$xrefExit/;
    }
}

###################################################################
# Step IIIa: create a temporary file for the main index
###################################################################
$temppage="$WEB_DIR/\#$WEBPAGE.html";

unlink($temppage) if (-e $temppage);
open(TMPPAGE, "> $temppage")
    || die ("Cannot create temporary web page $temppage, stopped");

&concatenate("$WEBPAGE.intro", TMPPAGE);

# write processing date and time
#print TMPPAGE "<P>\nRun on $now\n";

# (FF) Add an alphabetical index for fast access
print TMPPAGE "\n<h3>";
foreach $letter ("A".."Z") {
    print TMPPAGE "<a href=\"\#$letter\">$letter</a>\n";
}
print TMPPAGE "</h3>\n";

# start a two columns table
print TMPPAGE << "TABLE_BEGINNING";
<TABLE BORDER=0 WIDTH="100%">
<TR>
<TD valign=top>
TABLE_BEGINNING

# start with special characters
$letter = " ";
print TMPPAGE "<dl>\n";


###################################################################
# Step IIIb: create a temporary file for the two-level index
###################################################################
$twolevpage="$TWOLEVEL.html";
$twolevtemp="$WEB_DIR/\#$TWOLEVEL.html";

unlink($twolevtemp) if (-e $twolevtemp);
open(TMP2LEV, "> $twolevtemp")
    || die ("Cannot create temporary web page $twolevtemp, stopped");

&concatenate("$TWOLEVEL.intro", TMP2LEV);

# start the two-level index
print TMP2LEV << "TWO_LEVEL_BEGINNING";
<UL>
TWO_LEVEL_BEGINNING
$optimEntriesPerPage = 1.3 * sqrt $numEntriesRead;
$entriesInPage = 0; # how many entries written in this page?
$indexPageName = "t00";


# find the age of the younger of the entry intro and entry conclusion 
# files, so we can check whether we need to rewrite the HTML page.
$ENTNEWESTMOD = -M $ENTCONCL;
if (-M $ENTINTRO < $ENTNEWESTMOD) {
    $ENTNEWESTMOD = -M $ENTINTRO;
}

$prevdname = ""; # check for repeated entries

# sort the entries
@sortedentries = sort keys %entries;
#print @sortedentries;
$numEntries = 0;

#------------------------------------------------------------------------
#
# Step IIIc: write each entry to its own page, in main page index, and 
#	in the two-level index
#
#------------------------------------------------------------------------

print STDERR "Writing terms\n" if ($verbose);

for $ekey (@sortedentries) {
    %thisEntry = %{$entries{$ekey}};
    #print %thisEntry; print "\n";

    my($ename) = $thisEntry{NAME};
    my($tname) = $thisEntry{TNAME};
    my $dname = $thisEntry{DNAME};
    my $xname = $thisEntry{XNAME};
    if (defined $thisEntry{MODIFIED}) {
	$moddate = $thisEntry{MODIFIED};
    } else {
	$moddate = "sometime";
    }

    # check for repeated entry names.  This happens when I change the
    # file name for an entry, but forget to remove the old file.
    if ($dname eq $prevdname) {
	print "\n    *****Repeated entry: $dname\n";
    }
    $prevdname = $dname;

    $termpage="$OUT_DIR/$thisEntry{BASEFILENM}.html";
    $termurl ="$URL_DIR/$termpage";
    $termfile="$WEB_DIR/$termpage";

    $numEntries++;

    ###########################################################
    # Write an entry in the combined index page
    ###########################################################

    while (substr($ekey, 0, 1) gt $letter) {
	# finish previous letter
	print TMPPAGE "</dl>\n\n";

	# start new letter
	if ($letter eq " ") {
	    $letter = "A";
	} else {
	    $letter++;
	}
	if ($letter eq "M") {
	    # start new column
	    print TMPPAGE << "TABLE_NEXT_COLUMN";
</td>

<td valign=top>
TABLE_NEXT_COLUMN
	}
	print TMPPAGE "<a name=\"$letter\"><h2>$letter</h2>\n\n<dl>\n";
    }

    # write an entry in the main page
    print TMPPAGE "<dt><a href=\"$termpage\">$dname</a>\n";

    ###########################################################
    # Write an entry in the two-level index
    ###########################################################

    if ($entriesInPage == 0) {
	# start a new index page
	$indexPageName++;

	$indexPage = "$WEB_DIR/$indexPageName.html";

	unlink($indexPage) if (-e $indexPage);
	open(SUB2LEV, "> $indexPage")
	    || die ("Cannot create index web page $indexPage, stopped");
	&concatenate("${TWOLEVEL}page.intro", SUB2LEV);

	print TMP2LEV "<li><a href=\"$indexPageName.html\">$dname - ";
    }

    # write an entry in the second level page
    print SUB2LEV "<dt><a href=\"$termpage\">$dname</a>\n";
    $entriesInPage++;
    if ($entriesInPage > $optimEntriesPerPage) {
	# finish the current index page
	&concatenate("${TWOLEVEL}page.concl", SUB2LEV);
	close SUB2LEV;

	print TMP2LEV "$dname</a>\n";

	$entriesInPage = 0;
    }

    ###########################################################
    # Write the entry HTML page (if necessary)
    ###########################################################

    # should we write the HTML page?
    if ((! -e $termfile) || $writeAllPages
	|| (-C $termfile > -M "$TERMS_DIR/$thisEntry{BASEFILENM}.trm")
	|| (-C $termfile > $ENTNEWESTMOD)) {
	# write the page
	print STDERR "$tname, " if ($verbose);
    } else {
	# don't need to write the page
	print STDERR ", " if ($verbose); # just a "working" mark
	next;
    }

    unlink($termfile) if (-e $termfile);
    open(TERMPAGE, "> $termfile")
	|| die ("Cannot create term web page $termfile, stopped");

    # copy term page intro, replacing variables as appropriate
    open(FHANDLE, "< $ENTINTRO")
	|| die("Cannot open $ENTINTRO\n");
    $runtime = localtime;
    while (<FHANDLE>) {
	s/\$NAME/$ename/g;
	s/\$DNAME/$dname/g;
	s/\$TNAME/$tname/g;
	s/\$RUNDATE/$runtime/g;
	s/\$MODDATE/$moddate/g;
	s/\$URL/$termurl/g;
	print TERMPAGE $_;
    };
    close(FHANDLE);

    if (defined $thisEntry{TYPE}) {
	my($etype) = $thisEntry{TYPE};
	my($elongtype) = $types{$etype};
	$elongtype =~ tr/A-Z/a-z/; # make lower case
	$elongtype =~ s/s$//o; # make singluar (not plural)
	print TERMPAGE "<p>\n($elongtype)\n</p>\n\n";
    }

    print TERMPAGE "<p>\n<strong>Definition:</strong>\n";
    if (defined $thisEntry{DEFN}) {
	my($edefn) = $thisEntry{DEFN};
	# convert cross references ({...}) to href's
	&rewriteXrefs($edefn, $ename);
	# convert LaTeX expressions to HTML
	&rewriteLatex($edefn);
	print TERMPAGE "$edefn\n";
    } else {
	print TERMPAGE << "NO_DEFN_MESSAGE";
(no definition here, yet, but
<a href=\"../$MAINPAGE\#needHelp\">you can help</a>.)
NO_DEFN_MESSAGE
    }
    print TERMPAGE "</p>\n\n";

    if (defined $thisEntry{FORML}) {
	my($eformlDef) = $thisEntry{FORML};
#	# convert cross references ({...}) to href's
#	&rewriteXrefs($eformlDef, $ename);
#	# convert LaTeX expressions to HTML
#	&rewriteLatex($eformlDef);
	print TERMPAGE "<p>\n<strong>Formal Definition:</strong> $eformlDef\n</p>\n";
    }

    if (defined $thisEntry{XREFS}) {
	my($exrefs) = $thisEntry{XREFS};
	# change cross references ({...}) to href's
	&rewriteXrefs($exrefs, $ename);
	# convert LaTeX expressions to HTML
	&rewriteLatex($exrefs);
	# have exactly one space after a comma
	$exrefs =~ s|,\s*|, |go;
	print TERMPAGE "<p>\n<strong>See also</strong>\n$exrefs.\n</p>\n\n";
    }
    if (defined $thisEntry{AKA}) {
	my($ealiases) = $thisEntry{AKA};
	# have exactly one space after a comma
	$ealiases =~ s|,\s*|, |go;
	# change cross references ({...}) to href's
	&rewriteXrefs($ealiases, $ename);
	print TERMPAGE "<p>\n<strong>Also known as</strong> $ealiases.\n</p>\n\n";
    }
    if (defined $thisEntry{NOTES}) {
	my($enotes) = $thisEntry{NOTES};
	# convert cross references ({...}) to href's
	&rewriteXrefs($enotes, $ename);
	# convert LaTeX expressions to HTML
	&rewriteLatex($enotes);
	print TERMPAGE "<p>\n<em>Note:\n$enotes</em>\n</p>\n\n";
    }
    if (defined $thisEntry{AUTHOR}) {
	my($eauth) = $thisEntry{AUTHOR};
	$eauth =~ s| *([^,]+)|<a href="../$MAINPAGE\#author$1">$1</a>|go;
	# SKIMP write plural if more than one
	print TERMPAGE "<p>Author: $eauth</p>\n";
    }
    if (defined $thisEntry{IMPL}) {
	my($eimpls) = $thisEntry{IMPL};
	# rewrite HREFs with exit_nist script
	&rewriteHrefs($eimpls);
	# SKIMP write plural if more than one
	print TERMPAGE "<H2>Implementation</H2>\n$eimpls\n";
    }
    if (defined $thisEntry{LINKS} || defined $thisEntry{BIB}) {
	print TERMPAGE "<H2>More information</H2>\n";
    }
    if (defined $thisEntry{LINKS}) {
	my($elinks) = $thisEntry{LINKS};
	# rewrite HREFs with exit_nist script
	&rewriteHrefs($elinks);
	print TERMPAGE "$elinks\n";
    }
    if (defined $thisEntry{BIB}) {
	my($ebiblio) = $thisEntry{BIB};
	print TERMPAGE "<p>\n$ebiblio\n</p>\n";
    }
    print TERMPAGE "\n";

    # copy term page conclusion, replacing variables as appropriate
    open(FHANDLE, "< $ENTCONCL")
	|| die("Cannot open $ENTCONCL\n");
    while (<FHANDLE>) {
	s/\$NAME/$ename/g;
	s/\$DNAME/$dname/g;
	s/\$TNAME/$tname/g;
	s/\$RUNDATE/$runtime/g;
	s/\$MODDATE/$moddate/g;
	s/\$URL/$termurl/g;
	print TERMPAGE $_;
    };
    close(FHANDLE);

    close(TERMPAGE);
}

print STDERR "\n" if ($verbose);

print "Wrote $numEntries terms\n";

#------------------------------------------------------------------------
#
# Step IV: Finish main index and two-level index, backup old page, and
#	rename temporary page
#    a) Finish the main index, write authors and copy closing
#    b) Copy closing of two-level index
#
#------------------------------------------------------------------------

########################################
# IVa: Finish main index
########################################

# print any remaining letters, for completeness
while ("Z" gt $letter) {
    # finish previous letter
    print TMPPAGE "</dl>\n\n";

    # start new letter
    $letter++;
    print TMPPAGE "<h2><a name=\"$letter\">$letter</a></h2>\n\n<dl>\n";
}

# finish last letter
print TMPPAGE "</dl>\n\n"; # end of list and section

# finish two column table
print TMPPAGE << "TABLE_ENDING";
</td>
</tr>
</table>
TABLE_ENDING

print STDERR "\n" if ($verbose);

print "Wrote $numEntries terms\n";

# write authors

print STDERR "Writing authors\n" if ($verbose);

print TMPPAGE "<hr>\n";
print TMPPAGE "<h1>Contributors Index</h1>\n";
print TMPPAGE "<dl>\n";

for $akey (sort keys %authors) {
    print TMPPAGE "<dt><a name=\"author$akey\">$akey</a>\n";
    my $aentry = $authors{$akey};
    # "quote" any HTML special characters
    $aentry =~ s/&/&amp;/go;
    $aentry =~ s/</&lt;/go;
    $aentry =~ s/>/&gt;/go;
    print TMPPAGE "<dd>$aentry\n";
    # print e-mail address(es) or URL(s), if given
    if (defined $authemail{$akey}) {
	for $fld (split(/, */, $authemail{$akey})) {
	    if ($fld =~ /@/) {
		# e-mail
		print TMPPAGE "<a href=\"mailto:$fld\">$fld</a>\n";
	    } else {
		# URL
		print TMPPAGE "<a href=\"$fld\">$fld</a>\n";
	    }
	}
    }
}

print TMPPAGE "</dl>\n\n";

# copy the closing
&concatenate("$WEBPAGE.concl", TMPPAGE);

close TMPPAGE;

# backup old page and rename the temporary file

&backupMove($temppage, "$WEB_DIR/$MAINPAGE") if ! $justTesting;

########################################
# IVb: Finish two-level index
########################################

# if the index page isn't finished, do it now
if ($entriesInPage > 0) {
    # finish the current index page
    &concatenate("${TWOLEVEL}page.concl", SUB2LEV);
    close SUB2LEV;

    print TMP2LEV "$prevdname</a>\n";
}

print TMP2LEV "</UL>\n\n";

&concatenate("$TWOLEVEL.concl", TMP2LEV);

close TMP2LEV;

&backupMove($twolevtemp, "$WEB_DIR/$twolevpage") if ! $justTesting;

#------------------------------------------------------------------------
#
# Step V: write entries with implementations
#
#------------------------------------------------------------------------

# Step Va: select name and open the page

$pageroot="$WEBPAGE" . "Impl";
$fspagename="$WEB_DIR/$pageroot.html";
$temppage="$WEB_DIR/\#$pageroot.html";

unlink($temppage) if (-e $temppage);
open(TMPPAGE, "> $temppage")
    || die ("Cannot create temporary web page $temppage, stopped");

# Step Vb: copy the intro
&concatenate("$pageroot.intro", TMPPAGE);

# write processing date and time
print TMPPAGE "<P>\nRun on $now\n";

# Step Vc: write entries with implementations

print STDERR "Writing entries with implementation links\n" if ($verbose);

print TMPPAGE "<hr>\n";

print TMPPAGE "<ul>\n";

# go through all the entries and print those with implementations
for $ent (@sortedentries) {
    next if ! defined $entries{$ent}{IMPL};
    my $dname = $entries{$ent}{DNAME};
    my $eimpls = $entries{$ent}{IMPL};
    my $erelurl = "$OUT_DIR/$entries{$ent}{BASEFILENM}.html";
    print TMPPAGE "<li><a href=\"$erelurl\">$dname</a>: $eimpls\n";
}
print TMPPAGE "</ul>\n\n";

# Step Vd: copy the conclusion and close
&concatenate("$pageroot.concl", TMPPAGE);

close TMPPAGE;

# Step Ve: backup page and relink

&backupMove($temppage, $fspagename);

#------------------------------------------------------------------------
#
# Step VI: write area index page
#
#------------------------------------------------------------------------

print STDERR "Writing entries by area\n" if ($verbose);

# Step VIa: select name and open the page

$pageroot="$WEBPAGE" . "Area";
$fspagename="$WEB_DIR/$pageroot.html";
$temppage="$WEB_DIR/\#$pageroot.html";

unlink($temppage) if (-e $temppage);
open(TMPPAGE, "> $temppage")
    || die ("Cannot create temporary web page $temppage, stopped");

# Step VIb: copy the intro
&concatenate("$pageroot.intro", TMPPAGE);

# write processing date and time
print TMPPAGE "<P>\nRun on $now\n";

# Add links to each area for fast access
print TMPPAGE "\n<h3>Areas</h3>\n<ul>\n";
for $area (sort keys %areas) {
    print TMPPAGE "<li><a href=\"\#$area\">$areas{$area}</a>\n";
}
# add link to no area
print TMPPAGE "<li><a href=\"\#noarea\">Entries with No Area</a>\n";
print TMPPAGE "</ul>\n";

# Step VIc: write areas and entries

print TMPPAGE "<hr>\n";

sub printAreaEntry {
    my %thisEntry = %{$entries{$_[0]}};
    my $dname = $thisEntry{DNAME};
    my $erelurl = "$OUT_DIR/$thisEntry{BASEFILENM}.html";
    print TMPPAGE "<li><a href=\"$erelurl\">$dname</a>";
    if (defined $thisEntry{TYPE}) {
	my $etype = $thisEntry{TYPE};
	print TMPPAGE " [<strong>$etype</strong>]";
    }
    print TMPPAGE "\n";
}

for $area (sort keys %areas) {
    print TMPPAGE "<h2><a name=\"$area\">$areas{$area}</a></h2>\n";
    print TMPPAGE "<ul>\n";

    # go through all the entries and print those in this area
    for $ent (@sortedentries) {
	next if ! defined $entries{$ent}{AREA} ||
			$entries{$ent}{AREA} ne $area;
	&printAreaEntry($ent);
    }
    print TMPPAGE "</ul>\n\n";
}

# print any entries without an area
print TMPPAGE "<h2><a name=\"noarea\">Entries with No Area</a></h2>\n";
print TMPPAGE "<ul>\n";
for $ent (@sortedentries) {
    if (! defined $entries{$ent}{AREA}) {
	&printAreaEntry($ent);
    }
}
print TMPPAGE "</ul>\n\n";

# Step VId: copy the conclusion and close
&concatenate("$pageroot.concl", TMPPAGE);

close TMPPAGE;

# Step VIe: backup page and relink

&backupMove($temppage, $fspagename);

#------------------------------------------------------------------------
#
# Step VII: write type index page
#
#------------------------------------------------------------------------

print STDERR "Writing entries by type\n" if ($verbose);

# Step VIIa: select name and open the page

$pageroot="$WEBPAGE" . "Type";
$fspagename="$WEB_DIR/$pageroot.html";
$temppage="$WEB_DIR/\#$pageroot.html";

unlink($temppage) if (-e $temppage);
open(TMPPAGE, "> $temppage")
    || die ("Cannot create temporary web page $temppage, stopped");

# Step VIIb: copy the intro
&concatenate("$pageroot.intro", TMPPAGE);

# write processing date and time
print TMPPAGE "<P>\nRun on $now\n";

# Add links to each section for fast access
print TMPPAGE "\n<h3>Types</h3>\n<ul>\n";
for $tent (keys %types) {
    print TMPPAGE "<li><a href=\"\#$tent\">$types{$tent}</a>\n";
}
# add link to unclassified entries
print TMPPAGE "<li><a href=\"\#notype\">Entries with No Type</a>\n";
print TMPPAGE "</ul>\n";

# Step VIIc: write types and entries

print TMPPAGE "<hr>\n";

for $tent (keys %types) {
    print TMPPAGE "<h2><a name=\"$tent\">$types{$tent}</a></h2>\n";
    print TMPPAGE "<ul>\n";

    # go through all the entries and print those of this type
    for $ent (@sortedentries) {
	next if ! defined $entries{$ent}{TYPE} ||
			$entries{$ent}{TYPE} ne $tent;
	my $dname = $entries{$ent}{DNAME};
	my $erelurl = "$OUT_DIR/$entries{$ent}{BASEFILENM}.html";
	print TMPPAGE "<li><a href=\"$erelurl\">$dname</a>\n";
    }
    print TMPPAGE "</ul>\n\n";
}

# print those with no type
print TMPPAGE "<h2><a name=\"notype\">Entries with No Type</a></h2>\n";
print TMPPAGE "<ul>\n";
for $ent (@sortedentries) {
    if (! defined $entries{$ent}{TYPE}) {
	my $dname = $entries{$ent}{DNAME};
	my $erelurl = "$OUT_DIR/$entries{$ent}{BASEFILENM}.html";
	print TMPPAGE "<li><a href=\"$erelurl\">$dname</a>\n";
    }
}
print TMPPAGE "</ul>\n\n";

# Step VIId: copy the conclusion and close
&concatenate("$pageroot.concl", TMPPAGE);

close TMPPAGE;

# Step VIIe: backup page and relink

&backupMove($temppage, $fspagename);

exit;

# end of $Source: /home/black/DADS/dads/RCS/mkterms,v $
